---
# roles/dovecot/tasks/main.yml
- name: Download Dovecot imap
  apt:
    name: dovecot-imapd
    state: latest
- name: Download Dovecot pop3
  shell: DEBIAN_FRONTEND=noninteractive apt-get -q -y install dovecot-pop3d
  ignore_errors: yes
- name: Activates our virtualhost
  command: echo "restart dovecot now"
  notify:
    - restart dovecot
