---
# roles/php/tasks/main.yml
- name: install php
  apt:
    name: php
    state: latest
- name: install libapache2-mod-php
  apt:
    name: libapache2-mod-php
    state: latest
- name: install php-mysql
  apt:
    name: php-mysql
    state: latest
- name: install php-common
  apt:
    name: php-common
    state: latest
- name: install php-mbstring
  apt:
    name: php-mbstring
    state: latest
- name: install php-xmlrpc
  apt:
    name: php-xmlrpc
    state: latest
- name: install php-gd
  apt:
    name: php-gd
    state: latest
- name: install php-xml
  apt:
    name: php-xml
    state: latest
- name: install php-cli
  apt:
    name: php-cli
    state: latest
- name: install php-curl
  apt:
    name: php-curl
    state: latest